spring:
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudtype
    username: manager
    password: manager0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope:
              - "profile"
              - "email"
            redirect-uri: ${GOOGLE_OAUTH2_REDIRECT_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: never

jwt:
  secret: ${JWT_TOKEN_SECRET}
  access-token-expiration-millis: 1_800_000 # 30 minutes
  refresh-token-expiration-millis: 604_800_000 # 7 days

cors:
  allow-credentials: true
  allow-headers:
    - "*"
  allow-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allow-origins:
    - "http://localhost:3000"

frontend:
  auth-callback-url: "http://localhost:3000/oauth/callback"
